name: Build UI Bundle Zip File
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
      
jobs:
  build-ui-bundle:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1
    - name: Set up Node
      uses: actions/setup-node@v2.1.5
      with:
        node-version : '15'
    - name: Install gulp
      run: npm install -g gulp-cli
    - name: Install dependencies
      run: npm install
    - name: Build UI bundle
      run: gulp bundle
    - name: Upload UI bundle
      uses: actions/upload-artifact@v2
      with:
        name: sds-ui-bundle.zip
        path: build/